<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0.2 (Python 3.8.10 on linux)" generated="20230517 14:20:51.245" rpa="false" schemaversion="3">
<suite id="s1" name="Test Cases" source="/home/rently/Desktop/Robot/Test_Suite/Test_Cases.robot">
<test id="s1-t1" name="Testone" line="10">
<kw name="App_Launch" library="Global_Config">
<kw name="Open Application" library="AppiumLibrary">
<arg>${REMOTE_URL}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>appPackage=${PACKAGE_NAME}</arg>
<arg>appActivity=${Activity_NAME}</arg>
<arg>automationName=${Automation_NAME}</arg>
<arg>app=${app}</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20230517 14:20:51.551" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20230517 14:20:51.551" endtime="20230517 14:20:51.552"/>
</kw>
<msg timestamp="20230517 14:20:51.554" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20230517 14:20:51.554" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The application at '../Resources/app-release.apk' does not exist or is not accessible
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: The application at '../Resources/app-release.apk' does not exist or is not accessible
    at getResponseForW3CError (/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)</msg>
<status status="FAIL" starttime="20230517 14:20:51.364" endtime="20230517 14:20:51.554"/>
</kw>
<kw name="Sleep" library="BuiltIn">
<arg>5s</arg>
<doc>Pauses the test executed for the given time.</doc>
<status status="NOT RUN" starttime="20230517 14:20:51.554" endtime="20230517 14:20:51.554"/>
</kw>
<status status="FAIL" starttime="20230517 14:20:51.363" endtime="20230517 14:20:51.555"/>
</kw>
<status status="FAIL" starttime="20230517 14:20:51.363" endtime="20230517 14:20:51.555">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The application at '../Resources/app-release.apk' does not exist or is not accessible
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: The application at '../Resources/app-release.apk' does not exist or is not accessible
    at getResponseForW3CError (/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)</status>
</test>
<doc>Test Suite</doc>
<status status="FAIL" starttime="20230517 14:20:51.246" endtime="20230517 14:20:51.555"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Test Cases">Test Cases</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230517 14:20:51.554" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
